### PR TITLE
RRSet TTL modification, ref. issue #142

### PR DESCRIPTION
**Pull request by he32**
Instead of erring out on RRset TTL modification where the RRset contains
more than 1 RR, just adjust the TTL of all the RRs in the RRset.

Suggested fix for #142

Admittedly, this has not been tested...  Someone more familiar with the
code should make a statement whether this has a chance of actually solving
the problem.

There's also no notice that other RRs were modified, I don't know if there's
an appropriate mechanism to do that.

### CODE REVIEW

**Comment by he32** [comment]
Scratch that -- this will not reflect the update in the underlying db.
I will make another attempt, and do some actual testing first.

**Comment by msimerson** [comment]
Hi @he32 , thank you!  This looks good. I've only given it a quick glance but I think the reason your test fails is that you've added a couple zone records but haven't cleaned them up, and I think those extra artifacts are making a subsequent test fail:

````
t/12_records.t ......... 1591/? 
#   Failed test at t/12_records.t line 705.
#          got: '4'
#     expected: '2'
````

At least that's my theory.

**Comment by he32** [comment]
Aha!  OK, I'll take a closer look and see if there's a pattern to follow
to clean up those two records my test added.

**Comment by he32** [comment]
There, I finally managed to match up all the pieces, and the tests now complete successfully.

**Comment by msimerson** [comment]
Nice work, thanks @he32 !

**Pull request merged**
